### ISSUE TITLE
Accessing both databases in migrations

### ISSUE THREAD

**Issue by aaricpittman** [customink/secondbase#57]
I'm trying to access both databases in a secondbase migration to transfer data between the two. Unfortunately, ActiveRecord::Base.connection is pointing at the same connection as SecondBase::Base.connection. Thoughts on how I would do that?

**Comment by sarsena** [comment]
What does your database config look like?

**Comment by aaricpittman** [comment]
This is the rough structure.
```
development:

test:

production:

app_db:
  development:

  test:

  production:
```
